# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ohara < Formula
  desc "CLI for Ohara — agent-optimized documentation"
  homepage "https://ohara.dev"
  version "0.21.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Lackech/ohara/releases/download/v0.21.1/ohara_0.21.1_darwin_amd64.tar.gz"
      sha256 "74e7a082143260a3f0aa8f0df0ce9a912bfd8377db80c4c861f0750317aba5e5"

      define_method(:install) do
        bin.install "ohara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Lackech/ohara/releases/download/v0.21.1/ohara_0.21.1_darwin_arm64.tar.gz"
      sha256 "cccd6ed2bad1f940876c858c064949504a217b4ef49a2fadb8f42dbd3a22c081"

      define_method(:install) do
        bin.install "ohara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lackech/ohara/releases/download/v0.21.1/ohara_0.21.1_linux_amd64.tar.gz"
      sha256 "49c399865c5271e92640cdfc67121e6a3fdea5960fe2daf13100c2bf23e9ddbc"
      define_method(:install) do
        bin.install "ohara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lackech/ohara/releases/download/v0.21.1/ohara_0.21.1_linux_arm64.tar.gz"
      sha256 "bf03287ac12bb1cb11d9ed36d563097756e8ea066a9a41b12faa5369459786b4"
      define_method(:install) do
        bin.install "ohara"
      end
    end
  end
end
