# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ohara < Formula
  desc "CLI for Ohara — agent-optimized documentation"
  homepage "https://ohara.dev"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Lackech/ohara/releases/download/v0.17.0/ohara_0.17.0_darwin_amd64.tar.gz"
      sha256 "9e310e26a2f56ac122e0a1c13bf881da369395323e2d5c0df7788f9b2a11d5f0"

      define_method(:install) do
        bin.install "ohara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Lackech/ohara/releases/download/v0.17.0/ohara_0.17.0_darwin_arm64.tar.gz"
      sha256 "a33902551bf4d4f95f4232f0e24b397d7a8ebeb696fb0abaf7a373df3430086f"

      define_method(:install) do
        bin.install "ohara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lackech/ohara/releases/download/v0.17.0/ohara_0.17.0_linux_amd64.tar.gz"
      sha256 "a048a73446f38f21077680082f2893ac11af0ae81650a202fbfe2fb54163d19a"
      define_method(:install) do
        bin.install "ohara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lackech/ohara/releases/download/v0.17.0/ohara_0.17.0_linux_arm64.tar.gz"
      sha256 "933a05063c468fc21407b805c18ebec9ab0b9814f9504ec538cb3a398fc10ea5"
      define_method(:install) do
        bin.install "ohara"
      end
    end
  end
end
