# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ohara < Formula
  desc "CLI for Ohara — agent-optimized documentation"
  homepage "https://ohara.dev"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Lackech/ohara/releases/download/v0.9.0/ohara_0.9.0_darwin_amd64.tar.gz"
      sha256 "95e33ea342db9ac0cc3df4ab2518a0c43059ea7e92f13dc2b202c80ca427f18f"

      define_method(:install) do
        bin.install "ohara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Lackech/ohara/releases/download/v0.9.0/ohara_0.9.0_darwin_arm64.tar.gz"
      sha256 "7ea7664822d9d4dc53a95e3f9b2f98350d8db9d16734b1533f8a975890b91f94"

      define_method(:install) do
        bin.install "ohara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lackech/ohara/releases/download/v0.9.0/ohara_0.9.0_linux_amd64.tar.gz"
      sha256 "daf99fed729f53c56feedf8e84644772d0573028ea0d07a4865364a72e22990a"
      define_method(:install) do
        bin.install "ohara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lackech/ohara/releases/download/v0.9.0/ohara_0.9.0_linux_arm64.tar.gz"
      sha256 "87de24bb8acd3ef2c8388fdb9550b12f88ff7cf37d480eb9be9f9ec91851a68f"
      define_method(:install) do
        bin.install "ohara"
      end
    end
  end
end
